# Generated by Django 4.1.5 on 2023-01-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_pic", models.ImageField(upload_to="teams/pics/%Y/%m/%d/")),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=255)),
                ("facebook_link", models.URLField(max_length=100)),
                ("twitter_link", models.URLField(max_length=100)),
                ("google_plus_link", models.URLField(max_length=100)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
