# Generated by Django 4.1.5 on 2023-01-15 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_alter_car_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="created_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 1, 15, 17, 54, 53, 646708)
            ),
        ),
        migrations.AlterField(
            model_name="car", name="description", field=models.TextField(),
        ),
    ]
