# Generated by Django 4.1.5 on 2023-01-15 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_alter_car_created_date_alter_car_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="body_style",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="car",
            name="created_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 1, 15, 20, 55, 20, 645404)
            ),
        ),
    ]
