# Generated by Django 4.1.5 on 2023-01-19 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0006_car_body_style_alter_car_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="created_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 1, 19, 15, 3, 0, 720856)
            ),
        ),
    ]
