# Generated by Django 4.1.5 on 2023-01-20 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0007_alter_car_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="created_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 1, 20, 14, 33, 3, 59753)
            ),
        ),
    ]
